### ISSUE TITLE
Selecting the network interface with only IP addresses is unintuitive

### ISSUE THREAD

**Issue by andrijaantunovic** [gcupko00/NetworkSniffer#2]
The main program window has a "select IP address" drop-down menu, which displays IP addresses, but it doesn't say which network interface they belong to. This makes it unnecessarily complicated to select the interface you need, because if you don't know which IP corresponds to which interface, you need to look up the IP address using an external program like ipconfig.

The network interface selector can be much more intuitive by displaying both the network interface and the IP address in the drop-down menu.

![networksniffer_issue01](https://cloud.githubusercontent.com/assets/16625803/15592053/fddc9e1c-23a0-11e6-9939-4221817f81f0.png)

**Comment by gcupko00** [comment]
Know your IPs!

**Comment by andrijaantunovic** [comment]
It's not possible to "know your IPs" by heart, since they're dynamic. While you can find out the corresponding IP with an external program, it makes the process unnecessarily complicated for what is essentially a trivial problem to solve - just populate the drop-down with the interface name string along with the IP address.

**Comment by gcupko00** [comment]
Fixed
